### ISSUE TITLE
:D not for Linux? :(

### ISSUE THREAD

**Issue by arch-user-france1** [Togohogo1/TypeRacer-Bot#9]
Why is that. I have geckodriver for Linux

**Comment by kwangzera** [comment]
Unfortunately, this program has only been tested to work on windows. I'll keep this issue open for when I do get to implement a version that works on Linux. Feel free to submit a pull request if you want.

**Comment by arch-user-france1** [comment]
Oh I just forgot to say that it works
I had to change the driver to Firefox and then worked (I downloaded the Firefox driver mentioned manually btw.)
